-- 007_auth.sql
-- Authentication for the two principals the product has: DXG staff and presenters.
-- There is no self-service signup: staff accounts are created by a platform admin,
-- and presenter credentials are generated by DXG (SECURITY_MODEL §2, amended).
-- Additive only: new columns are nullable, new tables are new.
SET search_path TO pmp, public;

-- Staff sign in with a password. Stored as scrypt (salt + params + digest),
-- never reversible, never logged.
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_hash        text;
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_set_at      timestamptz;
ALTER TABLE users ADD COLUMN IF NOT EXISTS must_change_password boolean NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS failed_logins        int     NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS locked_until         timestamptz;
-- MFA lands before the pilot (NFR-SEC-02); the column exists now so enabling it
-- is not a schema change on a live database.
ALTER TABLE users ADD COLUMN IF NOT EXISTS mfa_secret           text;
ALTER TABLE users ADD COLUMN IF NOT EXISTS mfa_enrolled_at      timestamptz;

-- Presenter credentials are the same speaker_tokens rows, with a third kind:
-- an access code DXG generates and gives to the presenter. The same value can be
-- typed on the sign-in page or embedded in a link — one credential, two doors.
ALTER TABLE speaker_tokens DROP CONSTRAINT IF EXISTS speaker_tokens_kind_check;
ALTER TABLE speaker_tokens ADD CONSTRAINT speaker_tokens_kind_check
  CHECK (kind IN ('magic_link', 'one_time_code', 'access_code'));
-- The last four characters, so staff can tell a presenter which code is current
-- without the platform ever storing the code itself.
ALTER TABLE speaker_tokens ADD COLUMN IF NOT EXISTS code_hint text;
ALTER TABLE speaker_tokens ADD COLUMN IF NOT EXISTS issued_by uuid REFERENCES users(id);

-- One session table for both principals. Exactly one of user_id / speaker_id is set.
-- Named auth_sessions because `sessions` is already the schedule's conference
-- sessions — same word, unrelated domain.
CREATE TABLE IF NOT EXISTS auth_sessions (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  kind              text NOT NULL CHECK (kind IN ('staff', 'presenter')),
  user_id           uuid REFERENCES users(id),
  speaker_id        uuid REFERENCES speakers(id),
  client_id         uuid REFERENCES clients(id),
  token_hash        bytea NOT NULL UNIQUE,
  issued_at         timestamptz NOT NULL DEFAULT now(),
  last_seen_at      timestamptz NOT NULL DEFAULT now(),
  idle_expires_at   timestamptz NOT NULL,
  absolute_expires_at timestamptz NOT NULL,
  revoked_at        timestamptz,
  ip                inet,
  user_agent        text,
  CHECK ((user_id IS NOT NULL) <> (speaker_id IS NOT NULL))
);
CREATE INDEX IF NOT EXISTS auth_sessions_lookup_idx ON auth_sessions (token_hash) WHERE revoked_at IS NULL;
CREATE INDEX IF NOT EXISTS auth_sessions_user_idx ON auth_sessions (user_id);

-- Every authentication attempt is recorded, successful or not: a failed sign-in
-- is the signal that matters (SECURITY_MODEL §2).
CREATE TABLE IF NOT EXISTS auth_attempts (
  id          bigserial PRIMARY KEY,
  kind        text NOT NULL CHECK (kind IN ('staff', 'presenter')),
  identifier  text NOT NULL,            -- email or speaker email, never the secret
  outcome     text NOT NULL CHECK (outcome IN
                ('success', 'bad_credentials', 'locked', 'unknown_identity', 'expired', 'revoked')),
  ip          inet,
  user_agent  text,
  detail      jsonb NOT NULL DEFAULT '{}',
  occurred_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS auth_attempts_recent_idx ON auth_attempts (identifier, occurred_at DESC);

GRANT SELECT, INSERT, UPDATE, DELETE ON auth_sessions, auth_attempts TO pmp_app;
GRANT USAGE, SELECT ON SEQUENCE auth_attempts_id_seq TO pmp_app;
